#!/bin/bash

# NyaySathi Database Migration Setup
# This script provides two ways to apply database migrations:
# 1. Manual: Copy-paste SQL into Supabase Dashboard
# 2. Automatic: Using SQL file directly

echo "🚀 NyaySathi Database Migration Guide"
echo "======================================="
echo ""
echo "Your migration file is ready: supabase/migrations_department_system.sql"
echo ""
echo "📋 Method 1: Apply via Supabase Dashboard (Recommended for safety)"
echo "─────────────────────────────────────────────────────────────────"
echo "1. Go to: https://app.supabase.com"
echo "2. Select your project (grrpsdnwdrkemxlomvij)"
echo "3. Go to SQL Editor → New Query"
echo "4. Copy-paste the contents of: supabase/migrations_department_system.sql"
echo "5. Click 'Run'"
echo ""
echo "📋 Method 2: Apply via this script (requires psql)"
echo "─────────────────────────────────────────────────"
echo "1. Install PostgreSQL client: brew install postgresql (macOS)"
echo "2. Set environment variables:"
echo "   export DB_HOST='db.grrpsdnwdrkemxlomvij.supabase.co'"
echo "   export DB_PORT='5432'"
echo "   export DB_NAME='postgres'"
echo "   export DB_USER='postgres'"
echo "   export DB_PASSWORD='your-supabase-password'"
echo "3. Run: npm run migrate"
echo ""
echo "📋 Method 3: Create Tables Manually"
echo "────────────────────────────────────"
echo "If you prefer manual creation, follow this order:"
echo "1. departments (base table)"
echo "2. department_admins (references departments)"
echo "3. department_staff (references departments & department_admins)"
echo "4. staff_assignments (references complaints, staff, admins, departments)"
echo "5. complaint_notes"
echo "6. field_visits"
echo "7. department_analytics"
echo "8. staff_performance"
echo "9. Then run ALTER TABLE statements on complaints"
echo ""
echo "✅ After migration, verify tables in Supabase Dashboard"
echo "   Tables → Check for new tables listed above"
echo ""
